# Generated by Django 3.0.5 on 2024-03-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0019_patient_qrcode_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documents', models.ImageField(blank=True, null=True, upload_to='PatientDocuments/')),
            ],
        ),
    ]
