# Generated by Django 3.0.5 on 2024-03-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0020_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='patientId',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
